insert into gem_types (id, name, slug, color_hint) values
  ('agate', 'Agate', 'agate', '#6b7280'),
  ('alexandrite', 'Alexandrite', 'alexandrite', '#166534'),
  ('amber', 'Amber', 'amber', '#b45309'),
  ('amethyst', 'Amethyst', 'amethyst', '#7e22ce'),
  ('ametrine', 'Ametrine', 'ametrine', '#9333ea'),
  ('andalusite', 'Andalusite', 'andalusite', '#92400e'),
  ('apatite', 'Apatite', 'apatite', '#0891b2'),
  ('aquamarine', 'Aquamarine', 'aquamarine', '#0e7490'),
  ('aventurine', 'Aventurine', 'aventurine', '#15803d'),
  ('beryl', 'Beryl', 'beryl', '#65a30d'),
  ('bloodstone', 'Bloodstone', 'bloodstone', '#14532d'),
  ('carnelian', 'Carnelian', 'carnelian', '#c2410c'),
  ('cats-eye', 'Cat''s Eye', 'cats-eye', '#a16207'),
  ('chalcedony', 'Chalcedony', 'chalcedony', '#64748b'),
  ('chrysoberyl', 'Chrysoberyl', 'chrysoberyl', '#ca8a04'),
  ('chrysoprase', 'Chrysoprase', 'chrysoprase', '#16a34a'),
  ('citrine', 'Citrine', 'citrine', '#d97706'),
  ('colored-diamond', 'Colored Diamond', 'colored-diamond', '#4f46e5'),
  ('coral', 'Coral', 'coral', '#e11d48'),
  ('diamond', 'Diamond', 'diamond', '#94a3b8'),
  ('diopside', 'Diopside', 'diopside', '#047857'),
  ('emerald', 'Emerald', 'emerald', '#047857'),
  ('feldspar', 'Feldspar', 'feldspar', '#c084fc'),
  ('fluorite', 'Fluorite', 'fluorite', '#7c3aed'),
  ('garnet', 'Garnet', 'garnet', '#991b1b'),
  ('heliodor', 'Heliodor', 'heliodor', '#ca8a04'),
  ('iolite', 'Iolite', 'iolite', '#4338ca'),
  ('jade', 'Jade', 'jade', '#15803d'),
  ('jasper', 'Jasper', 'jasper', '#b91c1c'),
  ('kunzite', 'Kunzite', 'kunzite', '#db2777'),
  ('kyanite', 'Kyanite', 'kyanite', '#1d4ed8'),
  ('labradorite', 'Labradorite', 'labradorite', '#475569'),
  ('lapis-lazuli', 'Lapis Lazuli', 'lapis-lazuli', '#1d4ed8'),
  ('malachite', 'Malachite', 'malachite', '#15803d'),
  ('moissanite', 'Moissanite', 'moissanite', '#64748b'),
  ('moonstone', 'Moonstone', 'moonstone', '#64748b'),
  ('morganite', 'Morganite', 'morganite', '#fb7185'),
  ('obsidian', 'Obsidian', 'obsidian', '#111827'),
  ('onyx', 'Onyx', 'onyx', '#111827'),
  ('opal', 'Opal', 'opal', '#7dd3fc'),
  ('pearl', 'Pearl', 'pearl', '#f8fafc'),
  ('peridot', 'Peridot', 'peridot', '#84cc16'),
  ('prehnite', 'Prehnite', 'prehnite', '#a3e635'),
  ('quartz', 'Quartz', 'quartz', '#cbd5e1'),
  ('rose-quartz', 'Rose Quartz', 'rose-quartz', '#f9a8d4'),
  ('ruby', 'Ruby', 'ruby', '#9f1239'),
  ('sapphire', 'Sapphire', 'sapphire', '#155e75'),
  ('sardonyx', 'Sardonyx', 'sardonyx', '#9a3412'),
  ('scapolite', 'Scapolite', 'scapolite', '#a855f7'),
  ('serpentine', 'Serpentine', 'serpentine', '#4d7c0f'),
  ('spinel', 'Spinel', 'spinel', '#7c3aed'),
  ('sunstone', 'Sunstone', 'sunstone', '#ea580c'),
  ('tanzanite', 'Tanzanite', 'tanzanite', '#3730a3'),
  ('topaz', 'Topaz', 'topaz', '#0369a1'),
  ('tourmaline', 'Tourmaline', 'tourmaline', '#047857'),
  ('turquoise', 'Turquoise', 'turquoise', '#0891b2'),
  ('zircon', 'Zircon', 'zircon', '#0f766e'),
  ('zoisite', 'Zoisite', 'zoisite', '#2563eb')
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  color_hint = excluded.color_hint;
