import type { GemType } from "@gems/schemas";

export const worldwideGemTypes: GemType[] = [
  { id: "agate", name: "Agate", slug: "agate", colorHint: "#6b7280" },
  { id: "alexandrite", name: "Alexandrite", slug: "alexandrite", colorHint: "#166534" },
  { id: "amber", name: "Amber", slug: "amber", colorHint: "#b45309" },
  { id: "amethyst", name: "Amethyst", slug: "amethyst", colorHint: "#7e22ce" },
  { id: "ametrine", name: "Ametrine", slug: "ametrine", colorHint: "#9333ea" },
  { id: "andalusite", name: "Andalusite", slug: "andalusite", colorHint: "#92400e" },
  { id: "apatite", name: "Apatite", slug: "apatite", colorHint: "#0891b2" },
  { id: "aquamarine", name: "Aquamarine", slug: "aquamarine", colorHint: "#0e7490" },
  { id: "aventurine", name: "Aventurine", slug: "aventurine", colorHint: "#15803d" },
  { id: "beryl", name: "Beryl", slug: "beryl", colorHint: "#65a30d" },
  { id: "bloodstone", name: "Bloodstone", slug: "bloodstone", colorHint: "#14532d" },
  { id: "carnelian", name: "Carnelian", slug: "carnelian", colorHint: "#c2410c" },
  { id: "cats-eye", name: "Cat's Eye", slug: "cats-eye", colorHint: "#a16207" },
  { id: "chalcedony", name: "Chalcedony", slug: "chalcedony", colorHint: "#64748b" },
  { id: "chrysoberyl", name: "Chrysoberyl", slug: "chrysoberyl", colorHint: "#ca8a04" },
  { id: "chrysoprase", name: "Chrysoprase", slug: "chrysoprase", colorHint: "#16a34a" },
  { id: "citrine", name: "Citrine", slug: "citrine", colorHint: "#d97706" },
  { id: "colored-diamond", name: "Colored Diamond", slug: "colored-diamond", colorHint: "#4f46e5" },
  { id: "coral", name: "Coral", slug: "coral", colorHint: "#e11d48" },
  { id: "diamond", name: "Diamond", slug: "diamond", colorHint: "#94a3b8" },
  { id: "diopside", name: "Diopside", slug: "diopside", colorHint: "#047857" },
  { id: "emerald", name: "Emerald", slug: "emerald", colorHint: "#047857" },
  { id: "feldspar", name: "Feldspar", slug: "feldspar", colorHint: "#c084fc" },
  { id: "fluorite", name: "Fluorite", slug: "fluorite", colorHint: "#7c3aed" },
  { id: "garnet", name: "Garnet", slug: "garnet", colorHint: "#991b1b" },
  { id: "heliodor", name: "Heliodor", slug: "heliodor", colorHint: "#ca8a04" },
  { id: "iolite", name: "Iolite", slug: "iolite", colorHint: "#4338ca" },
  { id: "jade", name: "Jade", slug: "jade", colorHint: "#15803d" },
  { id: "jasper", name: "Jasper", slug: "jasper", colorHint: "#b91c1c" },
  { id: "kunzite", name: "Kunzite", slug: "kunzite", colorHint: "#db2777" },
  { id: "kyanite", name: "Kyanite", slug: "kyanite", colorHint: "#1d4ed8" },
  { id: "labradorite", name: "Labradorite", slug: "labradorite", colorHint: "#475569" },
  { id: "lapis-lazuli", name: "Lapis Lazuli", slug: "lapis-lazuli", colorHint: "#1d4ed8" },
  { id: "malachite", name: "Malachite", slug: "malachite", colorHint: "#15803d" },
  { id: "moissanite", name: "Moissanite", slug: "moissanite", colorHint: "#64748b" },
  { id: "moonstone", name: "Moonstone", slug: "moonstone", colorHint: "#64748b" },
  { id: "morganite", name: "Morganite", slug: "morganite", colorHint: "#fb7185" },
  { id: "obsidian", name: "Obsidian", slug: "obsidian", colorHint: "#111827" },
  { id: "onyx", name: "Onyx", slug: "onyx", colorHint: "#111827" },
  { id: "opal", name: "Opal", slug: "opal", colorHint: "#7dd3fc" },
  { id: "pearl", name: "Pearl", slug: "pearl", colorHint: "#f8fafc" },
  { id: "peridot", name: "Peridot", slug: "peridot", colorHint: "#84cc16" },
  { id: "prehnite", name: "Prehnite", slug: "prehnite", colorHint: "#a3e635" },
  { id: "quartz", name: "Quartz", slug: "quartz", colorHint: "#cbd5e1" },
  { id: "rose-quartz", name: "Rose Quartz", slug: "rose-quartz", colorHint: "#f9a8d4" },
  { id: "ruby", name: "Ruby", slug: "ruby", colorHint: "#9f1239" },
  { id: "sapphire", name: "Sapphire", slug: "sapphire", colorHint: "#155e75" },
  { id: "sardonyx", name: "Sardonyx", slug: "sardonyx", colorHint: "#9a3412" },
  { id: "scapolite", name: "Scapolite", slug: "scapolite", colorHint: "#a855f7" },
  { id: "serpentine", name: "Serpentine", slug: "serpentine", colorHint: "#4d7c0f" },
  { id: "spinel", name: "Spinel", slug: "spinel", colorHint: "#7c3aed" },
  { id: "sunstone", name: "Sunstone", slug: "sunstone", colorHint: "#ea580c" },
  { id: "tanzanite", name: "Tanzanite", slug: "tanzanite", colorHint: "#3730a3" },
  { id: "topaz", name: "Topaz", slug: "topaz", colorHint: "#0369a1" },
  { id: "tourmaline", name: "Tourmaline", slug: "tourmaline", colorHint: "#047857" },
  { id: "turquoise", name: "Turquoise", slug: "turquoise", colorHint: "#0891b2" },
  { id: "zircon", name: "Zircon", slug: "zircon", colorHint: "#0f766e" },
  { id: "zoisite", name: "Zoisite", slug: "zoisite", colorHint: "#2563eb" }
];
